### ISSUE TITLE
Add screenshots to documentation

### ISSUE THREAD

**Issue by marcio-pessoa** [marcio-pessoa/axes_controller#57]
The objective is just to share some App screenshots on README.md.
To do it, is necessary to run the App and take one or two screenshots.

**Comment by aliu691** [comment]
hi, please can you add a description to the issue

**Comment by marcio-pessoa** [comment]
hi, dear @aliu691

The objective is just to share some App screenshots on README.md.
To do it, is necessary to run the App and take one or two screenshots.

Best regards.

**Comment by aliu691** [comment]
oh cool,
I would do that

**Comment by marcio-pessoa** [comment]
So @aliu691 if you want, it is up to you.
